import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/CustomNavbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex flex-col w-screen h-screen  ${inter.className}`}>
        <div className="flex flex-none  w-full">
          <CustomNavbar />
        </div>
        <div className="grow h-full">{children}</div>
        <div className="w-full ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
